version: 0.2
phases:
  install:
    runtime-versions:
        java: openjdk8
        python: 3.7
    commands:
      -  pip install --upgrade 'six==1.15'
      -  pip install pre-commit cloudformation-cli-java-plugin
  build:
    commands:
      - pre-commit run --all-files
      - cd "$CODEBUILD_SRC_DIR/aws-ec2-enclavecertificateiamroleassociation"
      - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify --no-transfer-progress
    finally:
      - cat "$CODEBUILD_SRC_DIR/aws-ec2-enclavecertificateiamroleassociation/rpdk.log"
